#include <algorithm>
#include <cstdint>
#include <iostream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

#include <chess.hpp>

#include "koi/game_state.hpp"
#include "koi/position.hpp"

namespace {

void require(bool condition, std::string_view message) {
    if (!condition) throw std::runtime_error(std::string(message));
}

std::vector<std::string> sorted_moves(const std::vector<koi::Move>& moves) {
    std::vector<std::string> result;
    result.reserve(moves.size());
    for (const koi::Move& move : moves) result.push_back(move.uci());
    std::sort(result.begin(), result.end());
    return result;
}

std::vector<std::string> sorted_chess_moves(const chess::Board& board) {
    chess::Movelist native_moves;
    chess::movegen::legalmoves(native_moves, board);
    std::vector<std::string> result;
    result.reserve(native_moves.size());
    for (const chess::Move move : native_moves) {
        if (board.isLegal(move)) result.push_back(chess::uci::moveToUci(move));
    }
    std::sort(result.begin(), result.end());
    return result;
}

void require_consistent(const koi::GameState& state, std::string_view context) {
    const koi::PositionConsistencySnapshot snapshot = state.consistency_snapshot();
    require(snapshot.consistent(), context);
    require(snapshot.native_fen == state.fen(),
            "consistency snapshot must expose the native FEN authority");
    require(snapshot.native_legal_moves == sorted_moves(state.legal_moves()),
            "consistency snapshot must expose the native legal move authority");
}

std::uint32_t next_random(std::uint32_t& state) {
    state ^= state << 13U;
    state ^= state >> 17U;
    state ^= state << 5U;
    return state;
}

const koi::MoveMetadata& require_generated_metadata(const koi::GameState& state,
                                                    std::string_view uci,
                                                    std::vector<koi::MoveMetadata>& storage) {
    storage = state.legal_moves_with_metadata();
    const auto found = std::find_if(storage.begin(), storage.end(), [uci](const koi::MoveMetadata& metadata) {
        return metadata.move.uci() == uci;
    });
    require(found != storage.end(), "fixture move must be generated by native authority");
    return *found;
}

void compare_position(std::string_view fen) {
    koi::Position native(fen);
    const auto parsed = koi::GameState::from_fen(fen);
    require(parsed.has_value(), "shadow oracle must accept the native fixture FEN");
    const koi::GameState& oracle = *parsed;
    chess::Board chess_oracle;
    require(chess_oracle.setFen(fen), "chess.hpp must accept the differential fixture FEN");
    require(native.fen() == oracle.fen(), "native and shadow FENs must round-trip identically");
    require(sorted_moves(native.legal_moves()) == sorted_moves(oracle.legal_moves()) &&
                sorted_moves(native.legal_moves()) == sorted_chess_moves(chess_oracle),
            "native, compatibility, and chess.hpp legal move sets must match");
}

void test_fixture_differential() {
    for (const std::string_view fen : {
             "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
             "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
             "rnbqkbnr/pppp1ppp/8/3Pp3/8/8/PPP1PPPP/RNBQKBNR w KQkq e6 0 2",
             "4k3/P7/8/8/8/8/8/4K3 w - - 0 1",
             "r3k2r/pp2bppp/2p1pn2/8/2B5/2N1PN2/PPPQ1PPP/R3K2R w KQkq - 0 1",
         }) {
        compare_position(fen);
    }
}

void test_sequential_differential() {
    koi::Position native;
    koi::GameState shadow = koi::GameState::startpos();
    chess::Board chess_oracle;
    for (int ply = 0; ply < 80; ++ply) {
        const auto native_moves = sorted_moves(native.legal_moves());
        const auto shadow_moves = sorted_moves(shadow.legal_moves());
        require(native_moves == shadow_moves && native_moves == sorted_chess_moves(chess_oracle),
                "sequential legal move sets must remain equal");
        if (native_moves.empty()) break;
        const auto move = koi::Move::parse_uci(native_moves[static_cast<std::size_t>(ply) % native_moves.size()]);
        require(move.has_value(), "differential move must parse");
        require(native.apply_uci(native_moves[static_cast<std::size_t>(ply) % native_moves.size()]),
                "native differential move must apply");
        require(shadow.make_move(*move), "shadow differential move must apply");
        const chess::Move chess_move = chess::uci::uciToMove(chess_oracle, move->uci());
        require(chess_move != chess::Move::NO_MOVE && chess_oracle.isLegal(chess_move),
                "native move must remain legal in chess.hpp");
        chess_oracle.makeMove(chess_move);
        require(native.fen() == shadow.fen(), "native and shadow FENs must stay synchronized");
        require(native.fen() == chess_oracle.getFen(), "native FEN must stay synchronized with chess.hpp");
    }
}

void test_game_state_consistency_snapshot() {
    koi::GameState state = koi::GameState::startpos();
    for (const std::string_view uci : {
             "e2e4", "e7e5", "g1f3", "b8c6", "f1b5", "a7a6", "b5a4",
         }) {
        const auto move = koi::Move::parse_uci(uci);
        require(move.has_value() && state.make_move(*move),
                "consistency fixture move must be legal in both state authorities");
        const auto snapshot = state.consistency_snapshot();
        require(snapshot.consistent(), "native and shadow snapshots must remain consistent");
        require(snapshot.native_fen == state.fen(), "snapshot must report the native FEN");
        require(snapshot.native_legal_moves.size() == state.legal_moves().size(),
                "snapshot must report every native legal move");
        require(snapshot.native_castling_rights == snapshot.shadow_castling_rights &&
                    snapshot.native_en_passant_square == snapshot.shadow_en_passant_square &&
                    snapshot.native_halfmove_clock == snapshot.shadow_halfmove_clock &&
                    snapshot.native_fullmove_number == snapshot.shadow_fullmove_number &&
                    snapshot.native_repetition_count == snapshot.shadow_repetition_count,
                "snapshot must expose equal native and shadow rule-state fields");
    }
}

void test_fixed_seed_generated_move_replay_stays_consistent() {
    koi::GameState state = koi::GameState::startpos();
    std::uint32_t seed = 0x4B4F4931U;
    for (int ply = 0; ply < 192; ++ply) {
        require_consistent(state, "fixed-seed replay must begin each ply synchronized");
        const std::vector<koi::MoveMetadata> moves = state.legal_moves_with_metadata();
        if (moves.empty()) break;
        const koi::MoveMetadata& selected = moves[next_random(seed) % moves.size()];
        require(state.make_legal_move(selected),
                "generated metadata must pass the mirror legality transaction");
        require_consistent(state, "fixed-seed replay must remain synchronized after generated move");
    }
}

void test_special_generated_moves_are_transactional() {
    struct Fixture {
        std::string_view fen;
        std::string_view move;
    };
    for (const Fixture fixture : {
             Fixture{"r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1", "e1g1"},
             Fixture{"rnbqkbnr/pppp1ppp/8/3Pp3/8/8/PPP1PPPP/RNBQKBNR w KQkq e6 0 2", "d5e6"},
             Fixture{"4k3/P7/8/8/8/8/8/4K3 w - - 0 1", "a7a8q"},
         }) {
        const auto parsed = koi::GameState::from_fen(fixture.fen);
        require(parsed.has_value(), "special-move fixture must be valid");
        koi::GameState state = *parsed;
        const koi::PositionConsistencySnapshot before = state.consistency_snapshot();
        std::vector<koi::MoveMetadata> moves;
        const koi::MoveMetadata metadata = require_generated_metadata(state, fixture.move, moves);
        require(state.make_legal_move(metadata),
                "generated special move must pass the mirror legality transaction");
        require_consistent(state, "generated special move must preserve full mirror consistency");
        require(state.unmake_move(), "generated special move must be undoable");
        require(state.consistency_snapshot() == before,
                "unmaking a generated special move must restore the complete diagnostic snapshot");
    }
}

void test_fixed_seed_make_unmake_restores_diagnostic_snapshots() {
    koi::GameState state = koi::GameState::startpos();
    std::vector<koi::PositionConsistencySnapshot> snapshots;
    std::uint32_t seed = 0x53484144U;
    for (int ply = 0; ply < 96; ++ply) {
        snapshots.push_back(state.consistency_snapshot());
        const std::vector<koi::MoveMetadata> moves = state.legal_moves_with_metadata();
        if (moves.empty()) break;
        require(state.make_legal_move(moves[next_random(seed) % moves.size()]),
                "fixed-seed generated move must apply before unmake regression");
        require_consistent(state, "make sequence must remain synchronized before unmake regression");
    }
    while (!snapshots.empty()) {
        require(state.unmake_move(), "every generated move in the regression sequence must unmake");
        require(state.consistency_snapshot() == snapshots.back(),
                "unmake must restore the complete native/shadow diagnostic snapshot");
        snapshots.pop_back();
    }
}

void test_repetition_and_rejected_generated_metadata_preserve_consistency() {
    koi::GameState state = koi::GameState::startpos();
    for (const std::string_view uci : {
             "g1f3", "g8f6", "f3g1", "f6g8",
             "g1f3", "g8f6", "f3g1", "f6g8",
         }) {
        std::vector<koi::MoveMetadata> moves;
        const koi::MoveMetadata metadata = require_generated_metadata(state, uci, moves);
        require(state.make_legal_move(metadata), "repetition fixture move must apply transactionally");
    }
    const koi::PositionConsistencySnapshot repetition = state.consistency_snapshot();
    require(repetition.consistent() && repetition.native_repetition_count == 3 &&
                repetition.shadow_repetition_count == 3 &&
                repetition.native_repetition_sensitive && repetition.shadow_repetition_sensitive &&
                repetition.native_can_claim_threefold_repetition &&
                repetition.shadow_can_claim_threefold_repetition,
            "snapshot must report matching threefold repetition state");

    const koi::PositionConsistencySnapshot before_rejection = state.consistency_snapshot();
    std::vector<koi::MoveMetadata> moves = state.legal_moves_with_metadata();
    require(!moves.empty(), "repetition fixture must retain a legal generated move");
    moves.front().validation_token ^= 1U;
    require(!state.make_legal_move(moves.front()),
            "metadata whose generator provenance has changed must be rejected transactionally");
    require(state.consistency_snapshot() == before_rejection,
            "rejected generated metadata must leave the native/shadow snapshot unchanged");
}

} // namespace

int main() {
    try {
        test_fixture_differential();
        test_sequential_differential();
        test_game_state_consistency_snapshot();
        test_fixed_seed_generated_move_replay_stays_consistent();
        test_special_generated_moves_are_transactional();
        test_fixed_seed_make_unmake_restores_diagnostic_snapshots();
        test_repetition_and_rejected_generated_metadata_preserve_consistency();
        std::cout << "PASS native shadow differential tests\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "FAIL native shadow differential tests: " << error.what() << '\n';
        return 1;
    }
}
