# Embeds a PTX file as a C++ header of concatenated string literals.
#
# MSVC rejects single string literals longer than roughly 16k characters
# (C2026), and PTX can contain very long lines, so the content is escaped and
# split into chunks of a few thousand characters.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_ptx.cmake requires -DINPUT=<ptx> -DOUTPUT=<hpp>")
endif()

file(READ "${INPUT}" ptx)

string(REPLACE "\r" "" ptx "${ptx}")
string(REPLACE "\\" "\\\\" ptx "${ptx}")
string(REPLACE "\"" "\\\"" ptx "${ptx}")
string(REPLACE "\t" "\\t" ptx "${ptx}")
string(REPLACE "\n" "\\n" ptx "${ptx}")

set(chunk_size 4000)
string(LENGTH "${ptx}" total)
set(offset 0)
set(body "")
while(offset LESS total)
    math(EXPR remaining "${total} - ${offset}")
    if(remaining LESS chunk_size)
        set(length ${remaining})
    else()
        set(length ${chunk_size})
    endif()
    string(SUBSTRING "${ptx}" ${offset} ${length} chunk)
    # Never end a literal inside an escape sequence: a chunk that ends with a
    # backslash would escape the closing quote and run into the next line.
    while(length GREATER 1 AND chunk MATCHES "\\\\$")
        math(EXPR length "${length} - 1")
        string(SUBSTRING "${ptx}" ${offset} ${length} chunk)
    endwhile()
    string(APPEND body "    \"${chunk}\"\n")
    math(EXPR offset "${offset} + ${length}")
endwhile()

file(WRITE "${OUTPUT}"
"#pragma once\n"
"// Generated by cmake/embed_ptx.cmake from src/koi/gpu/koi_nnue_v5.cu; do not edit.\n"
"namespace koi::gpu {\n"
"inline constexpr char kNnueV5PtxSource[] =\n"
"${body}"
"    ;\n"
"} // namespace koi::gpu\n")
