# Embeds one PTX module per GPU architecture as a C++ header.
#
# MSVC rejects single string literals longer than roughly 16k characters
# (C2026), and PTX can contain very long lines, so every module is escaped and
# split into chunks of a few thousand characters.  The generated header defines
# `kNnueV5PtxVariants`, one entry per architecture; the runtime picks an entry
# with `select_ptx_variant` (see src/koi/gpu/ptx_variant.hpp).

if(NOT DEFINED INPUTS OR NOT DEFINED ARCHS OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR
        "embed_ptx.cmake requires -DINPUTS=<ptx list> -DARCHS=<arch list> -DOUTPUT=<hpp>")
endif()

list(LENGTH INPUTS input_count)
list(LENGTH ARCHS arch_count)
if(NOT input_count EQUAL arch_count)
    message(FATAL_ERROR "embed_ptx.cmake needs exactly one architecture per input PTX")
endif()

set(chunk_size 4000)
set(entries "")
math(EXPR last_index "${input_count} - 1")
foreach(index RANGE ${last_index})
    list(GET INPUTS ${index} input)
    list(GET ARCHS ${index} arch)
    math(EXPR major "${arch} / 10")
    math(EXPR minor "${arch} % 10")

    file(READ "${input}" ptx)
    string(REPLACE "\r" "" ptx "${ptx}")
    string(REPLACE "\\" "\\\\" ptx "${ptx}")
    string(REPLACE "\"" "\\\"" ptx "${ptx}")
    string(REPLACE "\t" "\\t" ptx "${ptx}")
    string(REPLACE "\n" "\\n" ptx "${ptx}")

    string(LENGTH "${ptx}" total)
    set(offset 0)
    set(body "")
    while(offset LESS total)
        math(EXPR remaining "${total} - ${offset}")
        if(remaining LESS chunk_size)
            set(length ${remaining})
        else()
            set(length ${chunk_size})
        endif()
        string(SUBSTRING "${ptx}" ${offset} ${length} chunk)
        # Never end a literal inside an escape sequence: a chunk that ends with
        # a backslash would escape the closing quote and run into the next line.
        while(length GREATER 1 AND chunk MATCHES "\\\\$")
            math(EXPR length "${length} - 1")
            string(SUBSTRING "${ptx}" ${offset} ${length} chunk)
        endwhile()
        string(APPEND body "        \"${chunk}\"\n")
        math(EXPR offset "${offset} + ${length}")
    endwhile()

    string(APPEND entries "    {${major}, ${minor},\n")
    string(APPEND entries "${body}")
    string(APPEND entries "    },\n")
endforeach()

file(WRITE "${OUTPUT}"
"#pragma once\n"
"// Generated by cmake/embed_ptx.cmake from src/koi/gpu/koi_nnue_v5.cu; do not edit.\n"
"#include \"koi/gpu/ptx_variant.hpp\"\n"
"\n"
"namespace koi::gpu {\n"
"\n"
"inline constexpr NnueV5PtxVariant kNnueV5PtxVariants[] = {\n"
"${entries}"
"};\n"
"\n"
"inline constexpr int kNnueV5PtxVariantCount = ${input_count};\n"
"\n"
"} // namespace koi::gpu\n")
