"""Fit classical evaluation term scales from `koi-eval-features` CSV dumps.

The tool is deliberately a report generator: it fits a regularized linear model
of the documented term subset against either the corpus labels (`cp`, side to
move relative) or the evaluator's own `total`, and writes a candidate header
plus a JSON report.  Nothing is adopted automatically - adopting a candidate
requires the repository gates (64/64 tactical suite, full CTest, equal-node
A/B), so this module never edits `src/`.

Usage:
    python tools/measurement/tune_classical.py --input features.csv \
        --header-out artifacts/training/tuned-classical.h --report-out report.json

The input CSV is produced by `koi-eval-features` with the columns
``fen,cp,phase,material,piece_square,...,total``.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import pathlib
import sys
from datetime import datetime, timezone

import numpy as np

TERMS = (
    "material",
    "piece_square",
    "mobility",
    "pawn_structure",
    "activity",
    "development",
    "center_control",
    "initiative",
    "king_safety",
    "king_activity",
    "passed_pawn",
    "tempo",
)
REPORT_SCHEMA = "koi-classical-tuning-report-v1"
HEADER_FORMAT = "koi-classical-tuning-v1"
DEFAULT_RIDGE = 1e-6


class TuningError(RuntimeError):
    """Raised for unusable input or a degenerate fit."""


def load_rows(path: pathlib.Path, limit: int = 0) -> list[dict[str, float | str]]:
    rows: list[dict[str, float | str]] = []
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        missing = [term for term in TERMS if term not in (reader.fieldnames or [])]
        if missing:
            raise TuningError(f"CSV is missing columns: {', '.join(missing)}")
        for raw in reader:
            row: dict[str, float | str] = {}
            try:
                for term in TERMS:
                    row[term] = float(raw[term])
                row["total"] = float(raw["total"])
            except (TypeError, ValueError) as error:
                raise TuningError(f"non-numeric term column: {error}") from error
            cp = (raw.get("cp") or "").strip()
            row["cp"] = float(cp) if cp else None
            rows.append(row)
            if limit > 0 and len(rows) >= limit:
                break
    if not rows:
        raise TuningError("no rows to fit")
    return rows


def fit_scales(
    rows: list[dict[str, float | str]], target: str, ridge: float = DEFAULT_RIDGE
) -> dict[str, float | int | dict[str, float]]:
    usable = [row for row in rows if row.get(target) is not None]
    if len(usable) < len(TERMS) + 1:
        raise TuningError(f"need at least {len(TERMS) + 1} rows with a {target!r} value, got {len(usable)}")
    if ridge < 0:
        raise TuningError("ridge must be non-negative")

    design = np.array([[float(row[term]) for term in TERMS] for row in usable], dtype=float)
    observed = np.array([float(row[target]) for row in usable], dtype=float)

    design_mean = design.mean(axis=0)
    observed_mean = observed.mean()
    centered_design = design - design_mean
    centered_observed = observed - observed_mean
    gram = centered_design.T @ centered_design + ridge * np.eye(len(TERMS))
    scales = np.linalg.solve(gram, centered_design.T @ centered_observed)
    offset = float(observed_mean - design_mean @ scales)

    current_prediction = design.sum(axis=1)
    fitted_prediction = offset + design @ scales
    return {
        "rows": int(len(usable)),
        "target": target,
        "ridge": float(ridge),
        "scales": {term: float(value) for term, value in zip(TERMS, scales)},
        "offset": offset,
        "current": _accuracy(observed, current_prediction),
        "fitted": _accuracy(observed, fitted_prediction),
    }


def _accuracy(observed: np.ndarray, predicted: np.ndarray) -> dict[str, float]:
    residual = observed - predicted
    variance = float(np.sum((observed - observed.mean()) ** 2))
    r2 = 1.0 - float(np.sum(residual**2)) / variance if variance > 0 else 0.0
    return {"mae": float(np.mean(np.abs(residual))), "r2": r2}


def generated_header(report: dict[str, float | int | dict[str, float]], corpus_sha256: str) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/measurement/tune_classical.py.",
        "// Candidate multiplicative term scales, NOT adopted weights: adoption",
        "// requires the 64/64 tactical gate, the full test suite, and an",
        "// equal-node A/B report.  The evaluator never reads this header.",
        f'inline constexpr const char* kTunedClassicalMetadataFormatVersion = "{HEADER_FORMAT}";',
        f'inline constexpr const char* kTunedClassicalCorpusSha256 = "{corpus_sha256}";',
        f'inline constexpr int kTunedClassicalRows = {report["rows"]};',
        f'inline constexpr double kTunedClassicalOffset = {report["offset"]:.10g};',
    ]
    scales = report["scales"]
    for term in TERMS:
        symbol = "".join(word.capitalize() for word in term.split("_"))
        lines.append(f"inline constexpr double kTunedClassicalScale{symbol} = {scales[term]:.10g};")
    lines.append("")
    return "\n".join(lines)


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Fit classical evaluation term scales from a CSV dump.")
    parser.add_argument("--input", type=pathlib.Path, required=True, help="CSV from koi-eval-features")
    parser.add_argument("--target", choices=("auto", "cp", "total"), default="auto")
    parser.add_argument("--ridge", type=float, default=DEFAULT_RIDGE)
    parser.add_argument("--limit", type=int, default=0, help="fit at most this many rows (0 = all)")
    parser.add_argument("--header-out", type=pathlib.Path)
    parser.add_argument("--report-out", type=pathlib.Path)
    return parser


def main(argv: list[str]) -> int:
    args = build_parser().parse_args(argv)
    try:
        rows = load_rows(args.input, args.limit)
        target = args.target
        if target == "auto":
            target = "cp" if any(row.get("cp") is not None for row in rows) else "total"
        report = fit_scales(rows, target, args.ridge)
    except TuningError as error:
        print(f"tune_classical.py: {error}", file=sys.stderr)
        return 2

    corpus_sha256 = sha256_file(args.input)
    report["schema"] = REPORT_SCHEMA
    report["created"] = datetime.now(timezone.utc).isoformat()
    report["corpus_sha256"] = corpus_sha256
    report["input"] = str(args.input)
    report["adopted"] = False

    if args.header_out is not None:
        args.header_out.parent.mkdir(parents=True, exist_ok=True)
        args.header_out.write_text(generated_header(report, corpus_sha256), encoding="utf-8")
    if args.report_out is not None:
        args.report_out.parent.mkdir(parents=True, exist_ok=True)
        args.report_out.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    current = report["current"]
    fitted = report["fitted"]
    print(
        f"tuned rows={report['rows']} target={report['target']} "
        f"current mae={current['mae']:.2f} r2={current['r2']:.4f} "
        f"fitted mae={fitted['mae']:.2f} r2={fitted['r2']:.4f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
